#!/bin/bash

# Check if an input file is provided
if [ -z "$1" ]; then
    echo "Usage: zrx <input_file.zrx>"
    exit 1
fi

gcc -o zrx_compiler src/zrx_compiler.c
./zrx_compiler "$1"
gcc output.c -o output
rm output.c
./output
